config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :drivers, only: [:new, :create]
  resources :driver_calls, only: [:create]
  
  get '/calls_queue', to: 'calls_queue#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_queue.rb
class CallQueue < ApplicationRecord
  belongs_to :driver

  scope :ordered, ->() { order(updated_at: :asc) }
end

app/models/driver.rb
class Driver < ApplicationRecord
  validates :name, presence: true

  def to_s
    name
  end
end

app/models/driver_call.rb
class DriverCall < ApplicationRecord
  MAX_WAIT_TIME = 10.minutes

  belongs_to :driver

  validates :final_time, presence: true
end

app/models/payment_queue.rb
class PaymentQueue < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/calls_queue_controller.rb
class CallsQueueController < ApplicationController
  def index
    @calls_queue = CallQueue.all
  end
end

app/controllers/driver_calls_controller.rb
class DriverCallsController < ApplicationController
  def create
    if DriverCallHandler.calls_next
      redirect_to root_path, notice: 'Call was created successfully'
    else
      redirect_to root_path, alert: 'Call could not be created'
    end
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end

  def create
    @driver = DriverCreator.new(driver_params)

    if @driver.save
      redirect_to root_path, notice: 'Driver was created successfully'
    else
      render :new
    end
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  def update
    @driver = Driver.find(params[:id])
    @driver.update(driver_params)

    respond_with @driver
  end

  private

  def driver_params
    params.require(:driver).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dashboard = Dashboard.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= form_for @driver do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/drivers/show.html.erb
<h1>Driver #<%= @driver.id %></h1>

<p>Name: <%= @driver.name %></p>

app/views/home/index.html.erb
<h1>Dashboard</h1>

<h3>Calls Queue</h3>
<table>
  <thead>
    <th>Id</th>
    <th>Driver</th>
    <th>Updated at</th>
  </thead>
  <tbody>
    <% @dashboard.calls_queue.each do |call| %>
      <tr>
        <td><%= call.id %></td>
        <td><%= call.driver %></td>
        <td><%= call.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<h3>Driver's list</h3>
<table>
  <thead>
    <th>Id</th>
    <th>Name</th>
  </thead>
  <tbody>
    <% @dashboard.drivers.each do |driver| %>
      <tr>
        <td><%= driver.id %></td>
        <td><%= driver.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Driver's calls list</h3>
<table>
  <thead>
    <th>Id</th>
    <th>Name</th>
  </thead>
  <tbody>
    <% @dashboard.driver_calls.each do |call| %>
      <tr>
        <td><%= call.id %></td>
        <td><%= call.driver %></td>
        <td><%= call.final_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_nav.html.erb
<h1>Menu</h1>
<ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'New driver', new_driver_path %></li>
  <li><%= link_to 'Call a driver', driver_calls_path, method: :post, data: { confirm: 'Are you want to confirm this call?' } %></li>
</ul>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotWait</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= alert || notice %>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>